name: ri
  channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>3.9
  - jupyterlab=3.3.0
  - jupyterlab-git=0.34.2
  - jupytext=1.14.0
  - matplotlib=3.5.1
  - numpy=1.22.3
  - nbdime=3.1.1
  - pandas=1.4.1
  - pytest=7.0.1
  - requests=2.28.1
  - seaborn=0.11.2
